targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
]

[licenses]
allow-osi-fsf-free = "either"
copyleft = "deny"
private = { ignore = true }

# note: this is temporary; a future update to RusTLS will
# remove ring from the dependency tree
[[licenses.clarify]]
crate = "ring"
expression = "ISC AND OpenSSL AND MIT"
license-files = [ { path = "LICENSE", hash = 0xbd0eed23 } ]

[advisories]
ignore = [
   { id="RUSTSEC-2024-0363", reason = "introduced by aries-askar, on which we are dependent; migrate away from sqlx 0.7" },
   { id="RUSTSEC-2021-0127", reason = "introduced by aries-askar, on which we are dependent; serde_cbor can be replaced by ciborium" },
]
