targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
]

[licenses]
allow-osi-fsf-free = "either"
copyleft = "deny"
private = { ignore = true }

# note: this is temporary; a future update to RusTLS will
# remove ring from the dependency tree
[[licenses.clarify]]
crate = "ring"
expression = "ISC AND OpenSSL AND MIT"
license-files = [ { path = "LICENSE", hash = 0xbd0eed23 } ]

[sources]
allow-git = [
    "https://github.com/marlonbaeten/rust-hpke",
    "https://github.com/marlonbaeten/aries-askar",
]

[advisories]
ignore = [
   { id="RUSTSEC-2024-0363", reason = "we cannot upgrade away from this without breaking compatibility with aries-askar" },
]
