[graph]
targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
]

[licenses]
private = { ignore = true }
allow = [
    "Unicode-3.0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-3-Clause",
    "ISC",
    "NCSA",
    "Zlib",
    "OpenSSL"
]

[advisories]
ignore = []
