apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 2
      containers:
        - name: demo-server
          image: us-central1-docker.pkg.dev/teaspoon-world-demo/tsp/openwallet-foundation-labs/tsp/demo-server:${TAG}
#          args: [ ${DOMAIN} ]
          ports:
            - name: http1
              containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000
  traffic:
    - percent: 100
      latestRevision: true