# This files defines the Python types for the generated PyO3 classes that are exposed directly
# without wrapping it in a Python class

class OwnedVid:
    @staticmethod
    def new_did_peer(url: str) -> OwnedVid: ...
    @staticmethod
    def new_did_webvh(did_name: str, transport: str) -> tuple[OwnedVid, str]: ...
    @staticmethod
    def bind(did: str, transport_url: str) -> OwnedVid: ...
    def json(self) -> str: ...
    def identifier(self) -> str: ...
    def endpoint(self) -> str: ...
