name: Docker

on:
  push:
    branches: [ "main" ]

permissions:
  packages: write
  contents: read
  
jobs:
  build-docker:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Create version tag
        shell: bash
        run: echo "tag=$(git show -s --format="%ct-%h" $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "ghcr.io/openwallet-foundation-labs/tsp/demo-intermediary:${{ env.tag }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max